# Generated by Django 5.0.6 on 2025-06-15 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de Notificación',
                'verbose_name_plural': 'Entregas de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificacionGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles_destinatarios', models.JSONField(help_text='Lista de roles que recibirán esta notificación')),
                ('mensaje', models.TextField()),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_notificacion', models.CharField(choices=[('ALERTA_STOCK', 'Alerta de Stock'), ('APROBACION_PENDIENTE', 'Aprobación Pendiente'), ('ESTADO_PEDIDO', 'Estado de Pedido'), ('PRODUCTO_ACTUALIZADO', 'Producto Actualizado'), ('CATEGORIA_NUEVA', 'Nueva Categoría'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=50)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='info', max_length=20)),
                ('url_accion', models.URLField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('usuarios_notificados', models.ManyToManyField(related_name='notificaciones_grupales_recibidas', through='notification.EntregaNotificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación Grupal',
                'verbose_name_plural': 'Notificaciones Grupales',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='entreganotificacion',
            name='notificacion_grupal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificaciongrupal'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(help_text='Contenido del mensaje de notificación')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación de la notificación')),
                ('leida', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída')),
                ('tipo_notificacion', models.CharField(choices=[('ALERTA_STOCK', 'Alerta de Stock'), ('APROBACION_PENDIENTE', 'Aprobación Pendiente'), ('ESTADO_PEDIDO', 'Estado de Pedido'), ('PRODUCTO_ACTUALIZADO', 'Producto Actualizado'), ('CATEGORIA_NUEVA', 'Nueva Categoría'), ('SISTEMA', 'Sistema')], default='SISTEMA', help_text='Tipo de notificación', max_length=50)),
                ('titulo', models.CharField(blank=True, help_text='Título breve de la notificación', max_length=200, null=True)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono (ej: ri-alert-line)', max_length=50, null=True)),
                ('color', models.CharField(default='info', help_text='Color de la notificación (success, warning, danger, info)', max_length=20)),
                ('url_accion', models.URLField(blank=True, help_text='URL a la que redirige al hacer clic en la notificación', null=True)),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario destinatario de la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificatio_usuario_18fc50_idx'), models.Index(fields=['fecha_hora'], name='notificatio_fecha_h_5e6a68_idx'), models.Index(fields=['tipo_notificacion'], name='notificatio_tipo_no_dddcad_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='entreganotificacion',
            unique_together={('notificacion_grupal', 'usuario')},
        ),
    ]
