# Generated by Django 5.0.6 on 2025-06-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo_notificacion',
            field=models.CharField(choices=[('ALERTA_STOCK', 'Alerta de Stock'), ('APROBACION_PENDIENTE', 'Aprobación Pendiente'), ('ESTADO_PEDIDO', 'Estado de Pedido'), ('PRODUCTO_ACTUALIZADO', 'Producto Actualizado'), ('CATEGORIA_NUEVA', 'Nueva Categoría'), ('SISTEMA', 'Sistema'), ('USUARIO_ESTADO_CAMBIADO', 'Estado de Usuario Cambiado'), ('USUARIO_CREADO', 'Usuario Creado')], default='SISTEMA', help_text='Tipo de notificación', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificaciongrupal',
            name='tipo_notificacion',
            field=models.CharField(choices=[('ALERTA_STOCK', 'Alerta de Stock'), ('APROBACION_PENDIENTE', 'Aprobación Pendiente'), ('ESTADO_PEDIDO', 'Estado de Pedido'), ('PRODUCTO_ACTUALIZADO', 'Producto Actualizado'), ('CATEGORIA_NUEVA', 'Nueva Categoría'), ('SISTEMA', 'Sistema'), ('USUARIO_ESTADO_CAMBIADO', 'Estado de Usuario Cambiado'), ('USUARIO_CREADO', 'Usuario Creado')], default='SISTEMA', max_length=50),
        ),
    ]
