# Generated by Django 5.0.6 on 2025-06-15 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_permissionmodule_userpermissiongroup_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PLANIFICADOR_COMPRAS', 'Planificador de Compras'), ('GERENTE_COMPRAS', 'Gerente de Compras'), ('ADMINISTRADOR_SISTEMA', 'Administrador del Sistema')], max_length=50, unique=True, verbose_name='Rol')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Grupo de Django')),
            ],
            options={
                'verbose_name': 'Configuración de Rol',
                'verbose_name_plural': 'Configuraciones de Roles',
                'ordering': ['role'],
            },
        ),
        migrations.DeleteModel(
            name='PermissionModule',
        ),
        migrations.RemoveField(
            model_name='userpermissiongroup',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='UserPermissionAssignment',
        ),
        migrations.DeleteModel(
            name='UserPermissionGroup',
        ),
    ]
