# Generated by Django 5.0.6 on 2025-06-25 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermissionconfig',
            options={'ordering': ['role'], 'verbose_name': 'Configuración de Permisos por Rol', 'verbose_name_plural': 'Configuraciones de Permisos por Rol'},
        ),
        migrations.RemoveField(
            model_name='rolepermissionconfig',
            name='is_active',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR_SISTEMA', 'Administrador del Sistema'), ('GERENTE_COMPRAS', 'Gerente de Compras'), ('PLANIFICADOR_COMPRAS', 'Planificador de Compras')], default='ADMINISTRADOR_SISTEMA', max_length=50),
        ),
        migrations.AlterField(
            model_name='rolepermissionconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='rolepermissionconfig',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_config', to='auth.group', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='rolepermissionconfig',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR_SISTEMA', 'Administrador del Sistema'), ('GERENTE_COMPRAS', 'Gerente de Compras'), ('PLANIFICADOR_COMPRAS', 'Planificador de Compras')], max_length=50, unique=True, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='rolepermissionconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
