# Generated by Django 5.2.2 on 2025-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_product_barcode_remove_product_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('published', 'Publicado'), ('draft', 'Borrador'), ('scheduled', 'Programado'), ('inactive', 'Inactivo')], default='draft', max_length=20),
        ),
    ]
