# Generated by Django 5.2.2 on 2025-06-07 21:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('tax_id', models.CharField(help_text='Número de identificación tributaria', max_length=20, unique=True, verbose_name='RUC/NIT')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Persona de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Principal')),
                ('phone_primary', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono Principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono Secundario')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Dirección Línea 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Línea 2')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Departamento/Estado')),
                ('country', models.CharField(default='Perú', max_length=100, verbose_name='País')),
                ('payment_terms', models.CharField(default='30 días', help_text='Ej: 30 días, 60 días, contado', max_length=100, verbose_name='Términos de Pago')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='Límite de Crédito')),
                ('category', models.CharField(choices=[('products', 'Productos'), ('services', 'Servicios'), ('materials', 'Materiales'), ('equipment', 'Equipos'), ('logistics', 'Logística'), ('other', 'Otros')], default='products', max_length=20, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='Proveedor Preferido')),
                ('rating', models.IntegerField(choices=[(1, '⭐ - Muy Malo'), (2, '⭐⭐ - Malo'), (3, '⭐⭐⭐ - Regular'), (4, '⭐⭐⭐⭐ - Bueno'), (5, '⭐⭐⭐⭐⭐ - Excelente')], default=3, verbose_name='Calificación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='suppliers/logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contacto Principal')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ecommerce.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Contacto del Proveedor',
                'verbose_name_plural': 'Contactos del Proveedor',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
