# Generated by Django 5.2.2 on 2025-06-07 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_supplier_suppliercontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_requerimiento', models.DateField(help_text='Fecha para cuando se necesita el requerimiento', verbose_name='Fecha Requerida')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='requerimientos/adjuntos/', verbose_name='Archivo Adjunto')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas y Observaciones')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso_cotizacion', 'En Proceso Cotización'), ('cotizado', 'Cotizado'), ('orden_generada', 'Orden Generada'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=25, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(help_text='Cantidad del producto solicitada', verbose_name='Cantidad Solicitada')),
                ('unidad_medida', models.CharField(default='unidad', help_text='Ej: unidad, kg, metros, litros, etc.', max_length=50, verbose_name='Unidad de Medida')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones específicas para este producto', null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product', verbose_name='Producto')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ecommerce.requirement', verbose_name='Requerimiento')),
            ],
            options={
                'verbose_name': 'Detalle de Requerimiento',
                'verbose_name_plural': 'Detalles de Requerimiento',
                'ordering': ['id'],
                'unique_together': {('requerimiento', 'producto')},
            },
        ),
    ]
