# Generated by Django 5.2.2 on 2025-06-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_requirement_requirementdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
