# Generated by Django 5.2.2 on 2025-06-08 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_product_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Envío')),
                ('metodo_envio', models.CharField(choices=[('email', 'Email Sistema'), ('whatsapp', 'WhatsApp Manual'), ('telefono', 'Teléfono Manual'), ('otro', 'Otro Manual')], max_length=50, verbose_name='Método Envío')),
                ('fecha_respuesta_esperada', models.DateField(verbose_name='Fecha Respuesta Esperada')),
                ('archivo_respuesta', models.FileField(blank=True, null=True, upload_to='cotizaciones/respuestas/', verbose_name='Archivo Respuesta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('respondido', 'Respondido'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email Enviado')),
                ('fecha_email_enviado', models.DateTimeField(blank=True, null=True)),
                ('notas_envio', models.TextField(blank=True, null=True, verbose_name='Notas del Envío')),
                ('enviado_manualmente', models.BooleanField(default=False, verbose_name='Enviado Manualmente')),
                ('fecha_envio_manual', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Envío Manual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado Por')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.supplier', verbose_name='Proveedor')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_cotizacion', to='ecommerce.requirement', verbose_name='Requerimiento')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
            ],
            options={
                'verbose_name': 'Envío de Cotización',
                'verbose_name_plural': 'Envíos de Cotizaciones',
                'ordering': ['-created_at'],
                'unique_together': {('requerimiento', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Respuesta')),
                ('terminos_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Términos de Pago')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('tiempo_entrega', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo de Entrega')),
                ('validez_cotizacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Validez de la Cotización')),
                ('incluye_igv', models.BooleanField(default=True, verbose_name='Incluye IGV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('envio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='ecommerce.enviocotizacion', verbose_name='Envío')),
            ],
            options={
                'verbose_name': 'Respuesta de Cotización',
                'verbose_name_plural': 'Respuestas de Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRespuestaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_code', models.CharField(help_text='Código del producto del sistema', max_length=20, verbose_name='Código Producto')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('cantidad_cotizada', models.PositiveIntegerField(default=1, verbose_name='Cantidad Cotizada')),
                ('nombre_producto_proveedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre según Proveedor')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('tiempo_entrega_especifico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo Entrega Específico')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones del Producto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product', verbose_name='Producto')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ecommerce.respuestacotizacion', verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Detalle Respuesta Cotización',
                'verbose_name_plural': 'Detalles Respuestas Cotizaciones',
                'ordering': ['id'],
            },
        ),
    ]
