# Generated by Django 5.2.2 on 2025-06-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_enviocotizacion_respuestacotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerespuestacotizacion',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible según el proveedor', verbose_name='Cantidad Disponible'),
        ),
        migrations.AddField(
            model_name='enviocotizacion',
            name='archivo_respuesta_cliente',
            field=models.FileField(blank=True, help_text='Excel completado por el proveedor con precios', null=True, upload_to='cotizaciones/respuestas_clientes/', verbose_name='Archivo Respuesta Cliente'),
        ),
        migrations.AddField(
            model_name='enviocotizacion',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento'),
        ),
        migrations.AddField(
            model_name='enviocotizacion',
            name='respuesta_procesada',
            field=models.BooleanField(default=False, help_text='Indica si el archivo de respuesta ya fue procesado automáticamente', verbose_name='Respuesta Procesada'),
        ),
        migrations.AddField(
            model_name='respuestacotizacion',
            name='procesado_automaticamente',
            field=models.BooleanField(default=False, help_text='Indica si fue creado automáticamente desde Excel', verbose_name='Procesado Automáticamente'),
        ),
    ]
