# Generated by Django 5.2.2 on 2025-06-09 01:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_detallerespuestacotizacion_cantidad_disponible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('1', 'DNI'), ('6', 'RUC'), ('4', 'Carnet de Extranjería'), ('7', 'Pasaporte')], default='1', max_length=2, verbose_name='Tipo de Documento')),
                ('document_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('customer_type', models.CharField(choices=[('persona_natural', 'Persona Natural'), ('persona_juridica', 'Persona Jurídica')], default='persona_natural', max_length=20, verbose_name='Tipo de Cliente')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('commercial_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Comercial')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('mobile_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Celular')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('sunat_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado SUNAT')),
                ('sunat_condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Condición SUNAT')),
                ('ubigeo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ubigeo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_frequent', models.BooleanField(default=False, verbose_name='Cliente Frecuente')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Límite de Crédito')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['first_name', 'business_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contacto Principal')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ecommerce.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contacto del Cliente',
                'verbose_name_plural': 'Contactos del Cliente',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Venta')),
                ('sale_type', models.CharField(choices=[('venta', 'Venta'), ('cotizacion', 'Cotización'), ('orden', 'Orden de Trabajo'), ('servicio', 'Servicio')], default='venta', max_length=20, verbose_name='Tipo de Venta')),
                ('guest_customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Cliente')),
                ('guest_customer_document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento del Cliente')),
                ('guest_customer_phone', models.CharField(blank=True, max_length=17, null=True, verbose_name='Teléfono del Cliente')),
                ('guest_customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Cliente')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto de IGV')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Descuento')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Tasa de IGV (%)')),
                ('includes_tax', models.BooleanField(default=True, verbose_name='Incluye IGV')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('yape', 'Yape'), ('plin', 'Plin'), ('credito', 'Crédito'), ('deposito', 'Depósito Bancario')], max_length=20, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('invoiced', 'Facturado'), ('delivered', 'Entregado'), ('paid', 'Pagado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('returned', 'Devuelto')], default='draft', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='ecommerce.customer', verbose_name='Cliente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento Monto')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Item de Venta',
                'verbose_name_plural': 'Items de Venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('yape', 'Yape'), ('plin', 'Plin'), ('credito', 'Crédito'), ('deposito', 'Depósito Bancario')], max_length=20, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Referencia')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ecommerce.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['document_number'], name='ecommerce_c_documen_24055b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='ecommerce_c_custome_f1cace_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='ecommerce_c_is_acti_70dce2_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_number'], name='ecommerce_s_sale_nu_f9a8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='ecommerce_s_status_6e89a3_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='ecommerce_s_sale_da_ec6fde_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer'], name='ecommerce_s_custome_10d524_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'product')},
        ),
    ]
