# Generated by Django 5.0.6 on 2025-06-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='history_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Historial'),
        ),
    ]
